
name: "Triager GHA without PR"
on:
    create: 
      branches:
        - '*'


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  # 通过  github action 的 VH 来执行 terraform command， 将 tfstate 同 lock 交及 S3 及 dynamodb
  # 不需要 terraform cloud 来操作

  # 当 tf plan 执行完后，还可以在 PR 上 create comment 将 tf plan的执行结果 输出。
jobs:
    tim-terraform:
        name: "terraform-name"
        runs-on: ubuntu-latest
        steps:
            - name: step 1 - checkout
              uses: actions/checkout@v2
              
            - name: step 2 - get terraform cli
              uses: hashicorp/setup-terraform@v2

            - name: step 3 - dummy step
              id: dummy
              run: echo ${AWS_ACCESS_KEY_ID}



