
name: "Terrform in GHA local"
on:
    push:
      branches:
        - main
    pull_request:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
    tim-terraform:
        name: "terraform-name"
        runs-on: ubuntu-latest
        steps:
            - name: step 1 - checkout
              uses: actions/checkout@v2
              
            - name: step 2 - get terraform cli
              uses: hashicorp/setup-terraform@v2

            - name: step 3 - dummy step
              id: dummy
              run: terraform version

            - name: dummy dummy
              id: dummy2
              run: echo `${{ github.ref }}`

            - name: step 4 - tf fmt
              id: fmt
              run: terraform fmt -check

            - name: step x - ll
              id: ddd
              run: ls -laht
            
            - name: step 5 - tf init
              id: init
              run: terraform init
            
            - name: step 6 - tf validate
              id: validate
              run: terraform validate

            - name: step x - ll
              id: dd
              run: echo `${{ steps.init.outcome }}` #  必须加上 ` 才会返回值

            - name: step x - 123
              id: multi_commands
              run: | 
                echo "`${{ steps.init.outcome }}`"
                echo "`${{ steps.init.outputs }}`"
                ls -laht
                echo "yeah ??"


            - name: step 7 - tf plan
              id: plan
              if: github.event_name == 'pull_request'
              run: terraform plan

            - name: step 8 - tf apply
              id: apply
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              run: terraform apply -auto-approve


