
name: "Terrform in GHA local"
on:
    push:
      branches:
        - main
    pull_request:


jobs:
    tim-terraform:
        name: "terraform-name"
        runs-on: ubuntu-latest
        steps:
            - name: step 1 - checkout
              uses: actions/checkout@v2
              
            - name: step 2 - get terraform cli
              uses: hashicorp/setup-terraform@v2

            - name: step 3 - dummy step
              id: dummy
              run: pwd

            - name: step 4 - dummy 2
              id: dummy2
              run: echo ${{ steps.dummy.outputs.stdout }}
            
            - name: step 5 - dummy 3
              id: dummy3
              run: echo ${{ steps.dummy.outcome.stdout }}


